config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :guestbooks do
    get 'confirm'
  end

  root to: "tenants#index"

  resources :tenants





end

app/models/guestbook.rb
require 'securerandom'

class Guestbook < ActiveRecord::Base
  validates :tenant_id, presence: true
  validates :title, presence: true
  validates :content, presence: true

  enum status: [ :created, :verified, :accepted, :declined ]


  def self.setup(data)
    gb = Guestbook.new(data)
    gb.status = :created
    gb.verification_token = SecureRandom.hex(64)
    saved = gb.save

    saved
  end


end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  before_save { self.email = email.downcase }

  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }


  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guestbooks_controller.rb
class GuestbooksController < ApplicationController
  before_action :set_guestbook, only: [:show, :edit, :update, :destroy]

  # GET /guestbooks
  # GET /guestbooks.json
  def index
    @guestbooks = Guestbook.all
  end

  # GET /guestbooks/1
  # GET /guestbooks/1.json
  def show
  end

  # GET /guestbooks/new
  def new
    @guestbook = Guestbook.new
  end

  # GET /guestbooks/1/edit
  def edit
  end

  # POST /guestbooks
  # POST /guestbooks.json
  def create
    saved = Guestbook.setup(guestbook_params)

    respond_to do |format|
      if saved
        format.html { redirect_to @guestbook, notice: 'Guestbook was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /guestbooks/1
  # PATCH/PUT /guestbooks/1.json
  def update
    respond_to do |format|
      if @guestbook.update(guestbook_params)
        format.html { redirect_to @guestbook, notice: 'Guestbook was successfully updated.' }
        format.json { render :show, status: :ok, location: @guestbook }
      else
        format.html { render :edit }
        format.json { render json: @guestbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guestbooks/1
  # DELETE /guestbooks/1.json
  def destroy
    @guestbook.destroy
    respond_to do |format|
      format.html { redirect_to guestbooks_url, notice: 'Guestbook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    token = params[:token]
    @item=Guestbook.find_by_id(params[:guestbook_id])
    if @item && @item.created?
      @item.update_attributes!(status: :verified) if @item.verification_token == token
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guestbook
      @guestbook = Guestbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guestbook_params
      params.require(:guestbook).permit(:tenant_id, :title, :content, :originator_email, :originator_name)
    end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: [:show, :edit, :update, :destroy]

  # GET /tenants
  def index
    @tenants = Tenant.all
  end

  # GET /tenants/1
  def show
    render "pages/#{@tenant.subfolder}/index"
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end


  # POST /tenants
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        format.html { redirect_to @tenant, notice: 'Tenant was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /tenants/1
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to @tenant, notice: 'Tenant was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tenants/1
  def destroy
    @tenant.destroy
    respond_to do |format|
      format.html { redirect_to tenants_url, notice: 'Tenant was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tenant_params
      params.require(:tenant).permit(:name, :subfolder)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password_encrypted, :salt)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guestbooks_helper.rb
module GuestbooksHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/guestbooks/_form.html.haml
= form_for @guestbook do |f|
  - if @guestbook.errors.any?
    #error_explanation
      %h2= "#{pluralize(@guestbook.errors.count, "error")} prohibited this guestbook from being saved:"
      %ul
        - @guestbook.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :tenant_id
    = f.number_field :tenant_id
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :status
    = f.number_field :status
  .field
    = f.label :originator_email
    = f.text_field :originator_email
  .field
    = f.label :originator_name
    = f.text_field :originator_name
  .actions
    = f.submit 'Save'

app/views/guestbooks/confirm.html.haml
%h1 Gästebucheintrag: E-Mail Bestätigung

%p
  - if @item
    Ihre E-Mailadresse wurde erfolgreich bestätigt. Ihr Gästebucheintrag wird nun geprüft und in Kürze erscheinen:

    %p
      %b= @item.title
      %p= @item.content
  - else
    Eintrag wurde nicht gefunden.

app/views/guestbooks/edit.html.haml
%h1 Editing guestbook

= render 'form'

= link_to 'Show', @guestbook
\|
= link_to 'Back', guestbooks_path

app/views/guestbooks/index.html.haml
%h1 Listing guestbook entries

%table.table.table-striped
  %tr
    %th Tenant
    %th Title
    %th Content
    %th Status
    %th Originator email
    %th Originator name
    %th
    %th
    %th

  - @guestbooks.each do |guestbook|
    %tr
      %td= guestbook.tenant_id
      %td= guestbook.title
      %td= guestbook.content
      %td= guestbook.status
      %td= guestbook.originator_email
      %td= guestbook.originator_name
      %td= link_to 'Show', guestbook
      %td= link_to 'Edit', edit_guestbook_path(guestbook)
      %td= link_to 'Destroy', guestbook, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Guestbook', new_guestbook_path

app/views/guestbooks/new.html.haml
%h1 New guestbook

= render 'form'

= link_to 'Back', guestbooks_path

app/views/guestbooks/show.html.haml
%p#notice= notice

%p
  %b Tenant:
  = @guestbook.tenant_id
%p
  %b Title:
  = @guestbook.title
%p
  %b Content:
  = @guestbook.content
%p
  %b Status:
  = @guestbook.status
%p
  %b Originator email:
  = @guestbook.originator_email
%p
  %b Originator name:
  = @guestbook.originator_name

= link_to 'Edit', edit_guestbook_path(@guestbook)
\|
= link_to 'Back', guestbooks_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger' }"}
      %button.close{type: "button", data: {dismiss:"alert"}, aria: {hidden:"true"}} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Sluiters
    = csrf_meta_tags
    = javascript_include_tag "application"
    = stylesheet_link_tag "application", media: "all"
  %body

    = render 'layouts/messages'

    = yield

app/views/pages/prinzengarde2015/index.html.haml
.container-fluid
  .row
    .span3
      %ul
        %li test
    .span9
      %h1 Prinzengarde 2015
      Bild von der Garde

app/views/tenants/_form.html.erb
<%= form_for(@tenant) do |f| %>
  <% if @tenant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tenant.errors.count, "error") %> prohibited this tenant from being saved:</h2>

      <ul>
      <% @tenant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>

    <%= f.label :subfolder %><br>
    <%= f.text_field :subfolder %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tenants/edit.html.erb
<h1>Editing tenant</h1>

<%= render 'form' %>

<%= link_to 'Show', @tenant %> |
<%= link_to 'Back', tenants_path %>

app/views/tenants/index.html.haml
Subfolder
%h1 Listing tenants

%table.table.table-striped
  %thead
    %tr
      %th ID
      %th Name
      %th Subfolder
      %th

  %tbody
    - @tenants.each do |tenant|
      %tr
        %td= tenant.id
        %td= tenant.name
        %td= tenant.subfolder
        %td
          = link_to tenant do
            %i.fa.fa-eye{title: 'Show'}
          = link_to edit_tenant_path(tenant) do
            %i.fa.fa-pencil{title: 'Edit'}
          = link_to tenant, method: :delete, data: { confirm: 'Are you sure?' } do
            %i.fa.fa-trash-o{title: 'Destroy'}

%br
= link_to new_tenant_path do
  .btn
    %i.fa.fa-plus
    New tenant

app/views/tenants/new.html.erb
<h1>New tenant</h1>

<%= render 'form' %>

<%= link_to 'Back', tenants_path %>

app/views/tenants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tenant.name %>
</p>

<%= link_to 'Edit', edit_tenant_path(@tenant) %> |
<%= link_to 'Back', tenants_path %>

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password_encrypted
    = f.text_field :password_encrypted
  .field
    = f.label :salt
    = f.text_field :salt
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Email
    %th Password encrypted
    %th Salt
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.email
      %td= user.password_encrypted
      %td= user.salt
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @user.email
%p
  %b Password encrypted:
  = @user.password_encrypted
%p
  %b Salt:
  = @user.salt

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path